name: Update Screenshot
on: 
  # schedule:
    # - cron: '0 16 * * *'
  push:
    branches: 
      - master

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
      # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
        token: ${{ github.token }} # optional, default is ${{ github.token }}
    - name: Download
      run: |
        pip install requests
        python main.py
        curl https://purge.jsdelivr.net/gh/oCoke/Friends@master/*.*
        curl https://purge.jsdelivr.net/gh/oCoke/Friends@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./
